### ISSUE TITLE
cli tool

### ISSUE THREAD

**Issue by blacksonic** [mzgol/check-dependencies#13]
is it possible to include a command line interface for it?
like install it globally and run it from project root as in npm-check-updates package

**Comment by mzgol** [comment]
I guess it should be possible, parameters may be mapped using [yargs](https://www.npmjs.com/package/yargs) or [minimist](https://www.npmjs.com/package/minimist).

I don't have time for this now but a PR would be welcome!

**Comment by TheSavior** [comment]
I'm going to jump in on this

**Comment by mzgol** [comment]
FYI: @TheSavior won't be able to finish his PR #19 soon so others are welcome to pick it up.

**Comment by mzgol** [comment]
I've published a beta version with the fix, install with `npm -g i check-dependencies@beta`. I'll publish a final version soon, I'd just want some feedback here first. If you could check that the proposed API is OK that'd be great, I'd rather not change it after the final release (in particular, check how `--scope-list` option works).

BTW, out of curiosity - do you all still need Node.js 0.10 support or would 0.12+ be enough?

**Comment by mzgol** [comment]
You can read how to use it here: https://github.com/mzgol/check-dependencies#cli

**Comment by mzgol** [comment]
`0.10.0` published.
