### ISSUE TITLE
Support NPM Peer Dependencies

### ISSUE THREAD

**Issue by mhupman** [mzgol/check-dependencies#9]
Some packages have started using the NPM "Peer Dependency" feature to avoid the same package being vendored over and over again.  When using the `onlySpecified` option, the "Peer Depedency" packages are identified as not being present in package.json when they probably should be.

See https://github.com/vojtajina/grunt-coffeelint/blob/master/package.json for an example package.

**Comment by mzgol** [comment]
Which version of `check-dependencies` do you use? Generally speaking, future npm will stop installing `peerDependencies` by default, they will just serve as guidelines and will warn on mismatch. So you'll need to add them to `devDependencies` anyway (`grunt-coffeelint` already does it btw).

**Comment by mhupman** [comment]
Interesting, I didn't know it was going to be removed.  I'm using `grunt-check-dependencies@0.9.0`, which is using `check-dependencies@0.9.2`.

**Comment by mzgol** [comment]
> Interesting, I didn't know it was going to be removed

It's not going to be removed, just the functionality will change. Read https://github.com/npm/npm/issues/6565#issuecomment-74971689 for a more detailed writeup.

**Comment by mzgol** [comment]
For now, you can use the [optionalScopeList](https://github.com/mzgol/check-dependencies#optionalscopelist) option, just set it to `['optionalDependencies', 'peerDependencies']`. But you should add `peerDependencies` to `dependencies` or `devDependencies` of your main package anyway because of these upcoming changes.

**Comment by mhupman** [comment]
Got it.  I'll just add it to my dependencies list.  Thanks!
